version: 0.0
os: linux
files:
  - source: target/demo-0.0.1-SNAPSHOT.jar
    destination: /home/app
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
file_exists_behavior: OVERWRITE